<?xml version="1.0"?>
<!DOCTYPE library[
    <!ELEMENT library (book+)>
    <!ELEMENT book (name, author, subject)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT subject (#PCDATA)> ]>

<library>
    <book>
        <name>Data Structure</name>
        <author>Coremann</author>
        <subject>Data Science</subject>
    </book>
    <book>
        <name>Cloud Computers</name>
        <author>XYZ</author>
        <subject>Virtualization</subject>
    </book>
    <book>
        <name>Java Programming</name>
        <author>ABC</author>
        <subject>Java</subject>
    </book>
    <book>
        <name>Algorithms</name>
        <author>Sudo</author>
        <subject>Python</subject>
    </book>
    <book>
        <name>Play With Docker</name>
        <author>Unknown</author>
        <subject>Cloud Computing</subject>
    </book>
    <book>
        <name>Fly With Python</name>
        <author>PQRS</author>
        <subject>Python</subject>
    </book>
</library>
