=== kishansinghverma/Learn_WebTech/web/Validate.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="mynamespace"
    xmlns="mynamespace"
    elementFormDefault="qualified">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="subject" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kishansinghverma/Learn_WebTech/web/Schema_Demo.xml
<?xml version="1.0" encoding="utf-8" ?>

<library
    xmlns="mynamespace"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="mynamespace Validate.xsd">
    <book>
        <name>Data Structure</name>
        <author>Coremann</author>
        <subject>Data Science</subject>
    </book>
    <book>
        <name>Cloud Computers</name>
        <author>XYZ</author>
        <subject>Virtualization</subject>
    </book>
    <book>
        <name>Java Programming</name>
        <author>ABC</author>
        <subject>Java</subject>
    </book>
    <book>
        <name>Algorithms</name>
        <author>Sudo</author>
        <subject>Python</subject>
    </book>
    <book>
        <name>Play With Docker</name>
        <author>Unknown</author>
        <subject>Cloud Computing</subject>
    </book>
    <book>
        <name>Fly With Python</name>
        <author>PQRS</author>
        <subject>Python</subject>
    </book>
</library>
